import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className}flex flex-col h-screen antialiased bg-gradient-to-r from-stone-200 via-stone-100 to-stone-200`}
      >
        <Header />
        <main className="mx-auto flex h-full max-w-7xl flex-col px-4 pt-24">
          {children}
        </main>
      </body>
    </html>
  )
}
